/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Students;

import java.awt.event.ItemListener;
import java.time.Month;
import java.time.YearMonth;
import java.util.Calendar;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author elisha
 */
public final class StudentForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StudentForm.class.getName());

    /**
     * Creates new form StudentForm
     */
    public StudentForm() {
        initComponents();
        
        loadYears();
        genderRadioGroup();
        departmentRadioGroup();
    }
    
    private static final String EMAIL_REGEX = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$";
    private static final String PASSWORD_REGEX = "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#$%^&*()\\-+])(?=\\S+$).{8,20}$";
    String email;
    String comfirmEmail;
    
    String password;
    String comfirmPassword;
    
    public boolean isValidPassword(){
        password = password_txt.getText();
        
        if(password==null){
            return false;
        }
        
        Pattern pattern  = Pattern.compile(PASSWORD_REGEX, Pattern.CASE_INSENSITIVE);
        Matcher matcher = pattern.matcher(password);
        return matcher.matches();
    }
    public boolean isValidEmail(){
        email = email_txt.getText();
        
        if(email == null){
            return false;
        }
        
        Pattern pattern = Pattern.compile(EMAIL_REGEX, Pattern.CASE_INSENSITIVE);
        Matcher matcher = pattern.matcher(email);
        return matcher.matches();
    }
    
    public void comfirmPassword(){
        password = password_txt.getText();
        comfirmPassword = comfirmpassword_txt.getText();
        
        if(!password.equals(comfirmPassword)){
            JOptionPane.showMessageDialog(this, "Password Doesn't Match", "ERROR", JOptionPane.ERROR_MESSAGE);
            comfirmpassword_txt.requestFocus();
        }
    }
    
    public void comfirmEmail(){
        email = email_txt.getText();
        comfirmEmail = emailComfirm_txt.getText();
        
        if(!email.equals(comfirmEmail)){
            JOptionPane.showMessageDialog(this, "Email Address does't Match", "ERROR", JOptionPane.ERROR_MESSAGE);
            emailComfirm_txt.requestFocus();
        }
    }
    public void genderRadioGroup(){
        ButtonGroup genderGroup = new ButtonGroup();
        genderGroup.add(maleRadioBtn);
        genderGroup.add(femaleRadioBtn);
    }
    
    public void departmentRadioGroup(){
        ButtonGroup departmentGroup = new ButtonGroup();
        departmentGroup.add(civilRadioBtn);
        departmentGroup.add(cseRadioBtn);
        departmentGroup.add(electricalRadioBtn);
        departmentGroup.add(ecRadioBtn);
        departmentGroup.add(mechanicalRadioBtn);
    }
    
    public final void loadYears(){
//        int currentYear = Calendar.getInstance().get(Calendar.YEAR);
        int endYear = 2010;
        int startYear = 1966;
        String yr;
        
        for(int i = startYear; i<=endYear; i++){
            yr = String.valueOf(i);
            yearCombo.addItem(yr);
        }
    }
    
    public void loadMonths(){
        String stringMonth;
        for(Month month : Month.values()){
            stringMonth = month.toString();
            monthCombo.addItem(stringMonth);
        }
    }
    
    String selectedYear;
    String selectedMonth;
    
    public void loadDays(String enteredmonth, String enteredYear){
        int month = 1;        
        int numberOfDays = 0;
        
        switch(enteredmonth){
            case "JANUARY" -> month = 1;
            case "FEBRUARY" -> month = 2;
            case "MARCH" -> month = 3;
            case "APRIL" -> month = 4;
            case "MAY" -> month = 5;
            case "JUNE" -> month = 6;
            case "JULY" -> month = 7;
            case "AUGUST" -> month = 8;
            case "SEPTEMBER" -> month = 9;
            case "OCTOBER" -> month = 10;
            case "NOVEMBER" -> month = 11;
            case "DECEMBER" -> month = 12;
            default -> {
            }
                    
        }
      
        YearMonth yearMonth = YearMonth.of(Integer.parseInt(enteredYear), month);
        
        numberOfDays = yearMonth.lengthOfMonth();
        
        for(int j = 1; j<=numberOfDays; j++ ){
            dayCombo.addItem(String.valueOf(j));
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        email_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        emailComfirm_txt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        password_txt = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        comfirmpassword_txt = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        yearCombo = new javax.swing.JComboBox<>();
        monthCombo = new javax.swing.JComboBox<>();
        dayCombo = new javax.swing.JComboBox<>();
        maleRadioBtn = new javax.swing.JRadioButton();
        femaleRadioBtn = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        civilRadioBtn = new javax.swing.JRadioButton();
        electricalRadioBtn = new javax.swing.JRadioButton();
        cseRadioBtn = new javax.swing.JRadioButton();
        mechanicalRadioBtn = new javax.swing.JRadioButton();
        ecRadioBtn = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        cancel_btn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel1.setText("New Student Registration Form");

        jLabel2.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        jLabel2.setText("Student First Name");

        jTextField1.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        jLabel3.setText("Student Last Name");

        email_txt.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        email_txt.addActionListener(this::email_txtActionPerformed);
        email_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                email_txtKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        jLabel4.setText("Email Address");

        jTextField3.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        jLabel5.setText("Comfirm Email Address");

        emailComfirm_txt.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        emailComfirm_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailComfirm_txtMouseClicked(evt);
            }
        });
        emailComfirm_txt.addActionListener(this::emailComfirm_txtActionPerformed);

        jLabel6.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        jLabel6.setText("Password");

        password_txt.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        password_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                password_txtMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        jLabel7.setText("Comfirm Password");

        comfirmpassword_txt.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        comfirmpassword_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comfirmpassword_txtMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        jLabel8.setText("Date of Birth");

        yearCombo.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        yearCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Year" }));
        yearCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                yearComboMouseClicked(evt);
            }
        });
        yearCombo.addActionListener(this::yearComboActionPerformed);

        monthCombo.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        monthCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Month" }));
        monthCombo.addActionListener(this::monthComboActionPerformed);

        dayCombo.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        dayCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Day" }));

        maleRadioBtn.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        maleRadioBtn.setText("Male");

        femaleRadioBtn.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        femaleRadioBtn.setText("Female");

        jLabel9.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        jLabel9.setText("Department");

        civilRadioBtn.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        civilRadioBtn.setText("Civil");

        electricalRadioBtn.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        electricalRadioBtn.setText("Electrical");

        cseRadioBtn.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        cseRadioBtn.setText("Computer Science & Engineering");

        mechanicalRadioBtn.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        mechanicalRadioBtn.setText("Mechanical");

        ecRadioBtn.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        ecRadioBtn.setText("Electronics & Communication");

        jButton1.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        jButton1.setText("Submit");

        cancel_btn.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        cancel_btn.setText("Cancel");
        cancel_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancel_btnMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Bitstream Charter", 1, 18)); // NOI18N
        jLabel10.setText("Your Data is Below:");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Bitstream Charter", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(comfirmpassword_txt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                                .addComponent(password_txt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(email_txt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(emailComfirm_txt, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(yearCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(monthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(dayCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(maleRadioBtn)
                                .addGap(18, 18, 18)
                                .addComponent(femaleRadioBtn)
                                .addGap(249, 249, 249)
                                .addComponent(jLabel10))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(civilRadioBtn)
                                    .addComponent(cseRadioBtn)
                                    .addComponent(electricalRadioBtn)
                                    .addComponent(ecRadioBtn)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(mechanicalRadioBtn)
                                            .addComponent(jButton1))
                                        .addGap(8, 8, 8)
                                        .addComponent(cancel_btn)))
                                .addGap(28, 28, 28)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jLabel1)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(emailComfirm_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(password_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(comfirmpassword_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dayCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maleRadioBtn)
                    .addComponent(femaleRadioBtn)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(civilRadioBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cseRadioBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(electricalRadioBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ecRadioBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mechanicalRadioBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancel_btn)
                            .addComponent(jButton1))
                        .addGap(40, 40, 40))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(15, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void yearComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearComboActionPerformed
        selectedYear = yearCombo.getSelectedItem().toString();
        loadMonths();
    }//GEN-LAST:event_yearComboActionPerformed

    private void monthComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthComboActionPerformed
        selectedMonth = monthCombo.getSelectedItem().toString();
        dayCombo.removeAllItems();
        dayCombo.addItem("Select Day");
        loadDays(selectedMonth, selectedYear);
    }//GEN-LAST:event_monthComboActionPerformed

    private void emailComfirm_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailComfirm_txtActionPerformed
        
    }//GEN-LAST:event_emailComfirm_txtActionPerformed

    private void email_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_txtActionPerformed
        boolean isValidEmail = isValidEmail();
        
        if(isValidEmail==false){
            JOptionPane.showMessageDialog(this, "Enter a valid Email Address", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_email_txtActionPerformed

    private void email_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_email_txtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_email_txtKeyTyped

    private void emailComfirm_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailComfirm_txtMouseClicked
        boolean isValidEmail = isValidEmail();
        
        if(isValidEmail==false){
            JOptionPane.showMessageDialog(this, "Enter a valid Email Address", "ERROR", JOptionPane.ERROR_MESSAGE);
            email_txt.requestFocus();
        }
    }//GEN-LAST:event_emailComfirm_txtMouseClicked

    private void password_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_password_txtMouseClicked
        comfirmEmail();
    }//GEN-LAST:event_password_txtMouseClicked

    private void comfirmpassword_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comfirmpassword_txtMouseClicked
        boolean isValidPassword = isValidPassword();
        
        if(isValidPassword == false){
            JOptionPane.showMessageDialog(this, "Enter a stronger Password.\n(8-20 characters, contain at least 1 letter and 1 digit)");
            password_txt.requestFocus();
        }
    }//GEN-LAST:event_comfirmpassword_txtMouseClicked

    private void yearComboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_yearComboMouseClicked
        comfirmPassword();
    }//GEN-LAST:event_yearComboMouseClicked

    private void cancel_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel_btnMouseClicked
        this.dispose();
    }//GEN-LAST:event_cancel_btnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new StudentForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton cancel_btn;
    private javax.swing.JRadioButton civilRadioBtn;
    private javax.swing.JPasswordField comfirmpassword_txt;
    private javax.swing.JRadioButton cseRadioBtn;
    private javax.swing.JComboBox<String> dayCombo;
    private javax.swing.JRadioButton ecRadioBtn;
    private javax.swing.JRadioButton electricalRadioBtn;
    private javax.swing.JTextField emailComfirm_txt;
    private javax.swing.JTextField email_txt;
    private javax.swing.JRadioButton femaleRadioBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JRadioButton maleRadioBtn;
    private javax.swing.JRadioButton mechanicalRadioBtn;
    private javax.swing.JComboBox<String> monthCombo;
    private javax.swing.JPasswordField password_txt;
    private javax.swing.JComboBox<String> yearCombo;
    // End of variables declaration//GEN-END:variables
}
